on:
  push:
    branches:
      - cd-bund

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 20
      - uses: actions/setup-go@v6
        with:
          go-version: '1.23.9'
      - run: npm ci
      - run: npm run build
        env:
          DEFAULT_COUNTRY_SECTION: switzerland
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/swiss/publiccode-editor.git
          npm run gdeploy -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
