on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile
      - run: yarn build:licenses
      - run: yarn build:wasm
      - run: yarn build
        env:
          ELASTIC_URL: "https://elasticsearch.developers.italia.it/indicepa_pec/_search"
          VALIDATOR_URL: "https://publiccode-validator.developers.italia.it/pc/validate"
          VALIDATOR_REMOTE_URL: "https://publiccode-validator.developers.italia.it/pc/validateURL"
      - run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/italia/publiccode-editor.git
          echo publiccode-editor.developers.italia.it > dist/CNAME

          yarn run deploy -m "Automated deployment: ${CIRCLE_SHA1} [ci skip]"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
